# Generated by Django 4.2.1 on 2023-06-21 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
