# Generated by Django 4.2.1 on 2023-06-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_notes_title_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
