# Generated by Django 4.2.1 on 2023-06-24 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.ManyToManyField(related_name='liked_students', through='sms.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
